import Head from "next/head";
import Layout from "@/components/Layout";
import Image from "next/image";
import profilePic from "../../public/images/profile/PortfolioProfile.webp";
import Animatedtext from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/styles/HireMe";
import LightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import TransitionEffect from "@/components/TransitionEffect";

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio | Awais Ashraf</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light md:pt-10 sm:pt-10 xs:pt-10">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className=" flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image
                src={profilePic}
                alt="Awais Ashraf"
                className="w-full h-auto  md:inline-block "
                priority
                sizes="(max-width:768px) 100vw,
                (max-width:1200px) 50vw,
                50vw"
              />
            </div>

            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <Animatedtext
                text="Turning Vision Into Reality With Code And Design."
                className="!text-6xl !text-left dark:text-light xl:!text-5xl lg:!text-center lg:!text-5xl sm:!text-3xl "
              />
              <p className="my-4 text-base font-medium dark:text-light md:text-sm sm:text-xs">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>

              <div className="flex items-center self-start mt-2 lg:self-center">
                {/* Resume Button - have to paste in 'public folder' */}
                <Link
                  href="/Awais Ashraf.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:border-light md:p-2 md:px-4 md:text-base"
                  download={true}
                >
                  Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>

                {/* Email Button */}
                <Link
                  href="mailto:awaisasharf420000@gmail.com"
                  target={"_blank"}
                  // className='ml-4 text-lg font-medium capitalize text-dark underline'
                  className="flex items-center bg-light text-dark p-2.5 px-8 rounded-lg text-lg font-semibold hover:bg-dark hover:text-light border-2 border-solid border-dark hover:border-dark ml-2 dark:hover:border-light md:text-base "
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>

        <HireMe />

        <div
        className="absolute right-8 bottom-8 inline-block w-24 lg:hidden md:hidden"
        >
          <Image src={LightBulb} alt="Awais Ashraf" className="w-full h-auto" />
        </div>

      </main>
    </>
  )
}






// import React from 'react'

// const Skills = () => {
//     return (
//         <div>
//             Skills
//         </div>
//     )
// }

// export default Skills







// Errors:
// scroll effect isn't working in "About.js - Experience"